openapi: 3.0.0
info:
  title: Skill Climbing
  version: 1.0.0
  description: スキルの積み上げアプリ

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://skill-climbing.onrender.com
    description: Production server

paths:
  /api/v1/stacks:
    get:
      summary: 積み上げ一覧
      operationId: api.v1.stacks.index
      tags:
        - Stack
      security: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stacks_StackList'
        '401':
          description: 認証エラー
    post:
      summary: 積み上げ作成
      operationId: api.v1.stacks.create
      tags:
        - Stack
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StacksCreateRequestBody'
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stacks_Stack'
        '401':
          description: 認証エラー
        '422':
          description: バリデーションエラー

  /api/v1/stacks/{stack_id}/introspections/{introspection_id}:
    get:
      summary: 積み上げの反省詳細API
      operationId: api.v1.stacks.introspections.show
      tags:
        - Stack
        - Introspection
      security: []
      parameters:
        - name: stack_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Stacks_Stack_Id'
        - name: introspection_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Stacks_Introspections_Introspection_Id'
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stacks_Introspections_Introspection'
        '401':
          description: 認証エラー
        '404':
          description: 積み上げが存在しない/反省が存在しない
    patch:
      summary: 積み上げの反省更新API
      operationId: api.v1.stacks.introspections.update
      tags:
        - Stack
        - Introspection
      security: []
      parameters:
        - name: stack_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Stacks_Stack_Id'
        - name: introspection_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Stacks_Introspections_Introspection_Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stacks_IntrospectionUpdateRequestBody'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stacks_Introspections_Introspection'
        '401':
          description: 認証エラー
        '404':
          description: 積み上げが存在しない
        '422':
          description: バリデーションエラー

  /api/v1/stacks/{stack_id}/introspections:
    post:
      summary: 積み上げの反省登録API
      operationId: api.v1.stacks.introspections.create
      tags:
        - Stack
        - Introspection
      security: []
      parameters:
        - name: stack_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Stacks_Stack_Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stacks_IntrospectionCreateRequestBody'
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stacks_Introspections_Introspection'
        '401':
          description: 認証エラー
        '404':
          description: 積み上げが存在しない
        '409':
          description: すでに反省が登録されている
        '422':
          description: バリデーションエラー

  /api/v1/skills:
    get:
      summary: スキルマスタデータ取得
      operationId: api.v1.skills.index
      tags:
        - Skill
      security: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skills_SkillList'
        '401':
          description: 認証エラー

  /api/v1/users/{user_id}:
    get:
      summary: ユーザーデータ詳細
      operationId: api.v1.users.show
      tags:
        - User
      security: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Users_User_Id'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users_User'
        '401':
          description: 認証エラー
        '404':
          description: ユーザーが存在しない
        '422':
          description: バリデーションエラー
      
    patch:
      summary: ユーザーデータ更新
      operationId: api.v1.users.update
      tags:
        - User
      security: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Users_User_Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateRequestBody'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users_User'
        '401':
          description: 認証エラー
        '404':
          description: ユーザーが存在しない
        '409':
          description: すでに登録されているメールアドレスを入力している
        '422':
          description: バリデーションエラー

components:
  schemas:
    Stacks_StackList:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/Stacks_Stack'

    Stacks_Stack:
      type: object
      required:
        - id
        - title
        - minutes
        - skill
        - description
        - stacked_at
        - created_at
        - updated_at
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/Stacks_Stack_Id'
          nullable: false
        title:
          allOf:
            - $ref: '#/components/schemas/Stacks_Stack_Title'
          nullable: false
        minutes:
          allOf:
            - $ref: '#/components/schemas/Stacks_Stack_Minutes'
          nullable: false
        skill:
          allOf:
            - $ref: '#/components/schemas/Skills_Skill'
          nullable: false
        description:
          allOf:
            - $ref: '#/components/schemas/Stacks_Stack_Description'
          nullable: true
        stacked_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false
        created_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false
        updated_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false

    Stacks_Introspections_Introspection:
      type: object
      required:
        - id
        - evaluation
        - reason
        - keeps
        - problems
        - tries
        - created_at
        - updated_at
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Introspection_Id'
          nullable: false
        evaluation:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Introspection_Evaluation'
          nullable: false
        reason:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Introspection_Reason'
          nullable: false
        keeps:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Stacks_Introspections_Keeps_Keep'
        problems:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Stacks_Introspections_Ploblems_Ploblem'
        tries:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Stacks_Introspections_Tries_Try'
        created_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false
        updated_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false

    Stacks_Introspections_Introspection_Id:
      type: integer
      description: 積み上げ反省ID
      example: 1

    Stacks_Introspections_Introspection_Evaluation:
      type: integer
      description: 積み上げの評価
      example: 85

    Stacks_Introspections_Introspection_Reason:
      type: string
      description: 積み上げの評価理由
      example: 今回は計画通りに積み上げられて良かったです。

    Stacks_Introspections_Keeps_Keep:
      type: object
      required:
        - id
        - content
        - created_at
        - updated_at
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Keeps_Keep_Id'
          nullable: false
        content:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Keeps_Keep_Content'
          nullable: false
        created_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false
        updated_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false

    Stacks_Introspections_Keeps_Keep_Id:
      type: integer
      description: 反省のKeepID
      example: 1
    Stacks_Introspections_Keeps_Keep_Content:
      type: string
      description: 反省のKeep項目
      example: 計画通りに積み上げられた

    Stacks_Introspections_Ploblems_Ploblem:
      type: object
      required:
        - id
        - content
        - created_at
        - updated_at
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Ploblems_Ploblem_Id'
          nullable: false
        content:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Ploblems_Ploblem_Content'
          nullable: false
        created_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false
        updated_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false

    Stacks_Introspections_Ploblems_Ploblem_Id:
      type: integer
      description: 反省のPloblemID
      example: 1
    Stacks_Introspections_Ploblems_Ploblem_Content:
      type: string
      description: 反省のPloblem項目
      example: スマホを触る時間が多かった

    Stacks_Introspections_Tries_Try:
      type: object
      required:
        - id
        - content
        - created_at
        - updated_at
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Tries_Try_Id'
          nullable: false
        content:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Tries_Try_Content'
          nullable: false
        created_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false
        updated_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false

    Stacks_Introspections_Tries_Try_Id:
      type: integer
      description: 反省のTryID
      example: 1
    Stacks_Introspections_Tries_Try_Content:
      type: string
      description: 反省のTry項目
      example: 作業時はスマホを寝室に置いておく

    Stacks_Stack_Id:
      type: integer
      description: 積み上げID
      example: 1

    Stacks_Stack_Title:
      type: string
      description: 積み上げタイトル
      example: 積み上げタイトル

    Stacks_Stack_Minutes:
      type: integer
      description: 積み上げ時間
      example: 100

    Stacks_Stack_Description:
      type: string
      description: 積み上げ内容
      example: 積み上げ内容

    Skills_SkillList:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/Skills_Skill'

    Skills_Skill:
      type: object
      required:
        - id
        - name
        - created_at
        - updated_at
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/Skills_Skill_Id'
          nullable: false
        name:
          allOf:
            - $ref: '#/components/schemas/Skills_Skill_Name'
          nullable: false
        created_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false
        updated_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false

    Skills_Skill_Id:
      type: integer
      description: スキルID
      example: 1

    Skills_Skill_Name:
      type: string
      description: スキル名
      example: Ruby

    Users_User:
      type: object
      required:
        - id
        - name
        - email
        - profile_content
        - group
        - created_at
        - updated_at
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/Users_User_Id'
          nullable: false
        name:
          allOf:
            - $ref: '#/components/schemas/Users_User_Name'
          nullable: false
        email:
          allOf:
            - $ref: '#/components/schemas/Users_User_Email'
          nullable: false
        profile_content:
          allOf:
            - $ref: '#/components/schemas/Users_User_ProfileContent'
          nullable: true
        group:
          allOf:
            - $ref: '#/components/schemas/Groups_Group'
          nullable: false
        created_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false
        updated_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false

    Users_User_Id:
      type: integer
      description: ユーザーID
      example: 1

    Users_User_Name:
      type: string
      description: ユーザー名
      example: 田中太郎

    Users_User_Email:
      type: string
      description: ユーザーのメールアドレス
      example: example@example.com

    Users_User_ProfileContent:
      type: string
      description: ユーザーのプロフィール文
      example: よろしくお願いします。

    Groups_Group:
      type: object
      required:
        - id
        - name
        - created_at
        - updated_at
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/Groups_Group_Id'
          nullable: false
        name:
          allOf:
            - $ref: '#/components/schemas/Groups_Group_Name'
          nullable: false
        created_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false
        updated_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false

    Groups_Group_Id:
      type: integer
      description: グループID
      example: 1

    Groups_Group_Name:
      type: string
      description: グループ名
      example: グループA

    DateTime:
      type: string
      format: date-time
      example: '2023-01-01T00:00:00+09:00'

    StacksCreateRequestBody:
      type: object
      required:
        - title
        - minutes
        - skill_id
        - description
        - stacked_at
      properties:
        title:
          allOf:
            - $ref: '#/components/schemas/Stacks_Stack_Title'
          nullable: false
        minutes:
          allOf:
            - $ref: '#/components/schemas/Stacks_Stack_Minutes'
          nullable: false
        skill_id:
          allOf:
            - $ref: '#/components/schemas/Skills_Skill_Id'
          nullable: false
        description:
          allOf:
            - $ref: '#/components/schemas/Stacks_Stack_Description'
          nullable: true
        stacked_at:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          nullable: false

    Stacks_IntrospectionCreateRequestBody:
      type: object
      required:
        - evaluation
        - reason
        - keep_contents
        - problem_contents
        - try_contents
      properties:
        evaluation:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Introspection_Evaluation'
          nullable: false
        reason:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Introspection_Reason'
          nullable: false
        keep_contents:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Keeps_Keep_Content'
        problem_contents:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Ploblems_Ploblem_Content'
        try_contents:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Tries_Try_Content'

    Stacks_IntrospectionUpdateRequestBody:
      type: object
      required:
        - evaluation
        - reason
        - keep_contents
        - problem_contents
        - try_contents
      properties:
        evaluation:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Introspection_Evaluation'
          nullable: false
        reason:
          allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Introspection_Reason'
          nullable: false
        keep_contents:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Keeps_Keep_Content'
        problem_contents:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Ploblems_Ploblem_Content'
        try_contents:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Stacks_Introspections_Tries_Try_Content'

    UserUpdateRequestBody:
      type: object
      required:
        - name
        - email
        - profile_content
        - group_id
      properties:
        name:
          allOf:
            - $ref: '#/components/schemas/Users_User_Name'
          nullable: false
        email:
          allOf:
            - $ref: '#/components/schemas/Users_User_Email'
          nullable: false
        profile_content:
          allOf:
            - $ref: '#/components/schemas/Users_User_ProfileContent'
          nullable: true
        group_id:
          allOf:
            - $ref: '#/components/schemas/Groups_Group_Id'
          nullable: true
