/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GroupsGroupListInner,
} from '../models';
import {
    GroupsGroupListInnerFromJSON,
    GroupsGroupListInnerToJSON,
} from '../models';

export interface ApiV1GroupsIndexRequest {
    name?: string;
}

/**
 * 
 */
export class GroupApi extends runtime.BaseAPI {

    /**
     * グループ一覧
     */
    async apiV1GroupsIndexRaw(requestParameters: ApiV1GroupsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupsGroupListInner>>> {
        const queryParameters: any = {};

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/groups`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupsGroupListInnerFromJSON));
    }

    /**
     * グループ一覧
     */
    async apiV1GroupsIndex(requestParameters: ApiV1GroupsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupsGroupListInner>> {
        const response = await this.apiV1GroupsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
