/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StacksIntrospectionCreateRequestBody,
  StacksIntrospectionUpdateRequestBody,
  StacksIntrospectionsIntrospection,
} from '../models';
import {
    StacksIntrospectionCreateRequestBodyFromJSON,
    StacksIntrospectionCreateRequestBodyToJSON,
    StacksIntrospectionUpdateRequestBodyFromJSON,
    StacksIntrospectionUpdateRequestBodyToJSON,
    StacksIntrospectionsIntrospectionFromJSON,
    StacksIntrospectionsIntrospectionToJSON,
} from '../models';

interface ApiV1StacksIntrospectionsCreateRequest {
    stackId: number;
    stacksIntrospectionCreateRequestBody: StacksIntrospectionCreateRequestBody;
}

interface ApiV1StacksIntrospectionsShowRequest {
    stackId: number;
}

interface ApiV1StacksIntrospectionsUpdateRequest {
    stackId: number;
    stacksIntrospectionUpdateRequestBody: StacksIntrospectionUpdateRequestBody;
}

/**
 * 
 */
export class IntrospectionApi extends runtime.BaseAPI {

    /**
     * 積み上げの反省登録API
     */
    async apiV1StacksIntrospectionsCreateRaw(requestParameters: ApiV1StacksIntrospectionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StacksIntrospectionsIntrospection>> {
        if (requestParameters.stackId === null || requestParameters.stackId === undefined) {
            throw new runtime.RequiredError('stackId','Required parameter requestParameters.stackId was null or undefined when calling apiV1StacksIntrospectionsCreate.');
        }

        if (requestParameters.stacksIntrospectionCreateRequestBody === null || requestParameters.stacksIntrospectionCreateRequestBody === undefined) {
            throw new runtime.RequiredError('stacksIntrospectionCreateRequestBody','Required parameter requestParameters.stacksIntrospectionCreateRequestBody was null or undefined when calling apiV1StacksIntrospectionsCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/stacks/{stack_id}/introspections`.replace(`{${"stack_id"}}`, encodeURIComponent(String(requestParameters.stackId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StacksIntrospectionCreateRequestBodyToJSON(requestParameters.stacksIntrospectionCreateRequestBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StacksIntrospectionsIntrospectionFromJSON(jsonValue));
    }

    /**
     * 積み上げの反省登録API
     */
    async apiV1StacksIntrospectionsCreate(requestParameters: ApiV1StacksIntrospectionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StacksIntrospectionsIntrospection> {
        const response = await this.apiV1StacksIntrospectionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 積み上げの反省詳細API
     */
    async apiV1StacksIntrospectionsShowRaw(requestParameters: ApiV1StacksIntrospectionsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StacksIntrospectionsIntrospection>> {
        if (requestParameters.stackId === null || requestParameters.stackId === undefined) {
            throw new runtime.RequiredError('stackId','Required parameter requestParameters.stackId was null or undefined when calling apiV1StacksIntrospectionsShow.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/stacks/{stack_id}/introspection`.replace(`{${"stack_id"}}`, encodeURIComponent(String(requestParameters.stackId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StacksIntrospectionsIntrospectionFromJSON(jsonValue));
    }

    /**
     * 積み上げの反省詳細API
     */
    async apiV1StacksIntrospectionsShow(requestParameters: ApiV1StacksIntrospectionsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StacksIntrospectionsIntrospection> {
        const response = await this.apiV1StacksIntrospectionsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 積み上げの反省更新API
     */
    async apiV1StacksIntrospectionsUpdateRaw(requestParameters: ApiV1StacksIntrospectionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StacksIntrospectionsIntrospection>> {
        if (requestParameters.stackId === null || requestParameters.stackId === undefined) {
            throw new runtime.RequiredError('stackId','Required parameter requestParameters.stackId was null or undefined when calling apiV1StacksIntrospectionsUpdate.');
        }

        if (requestParameters.stacksIntrospectionUpdateRequestBody === null || requestParameters.stacksIntrospectionUpdateRequestBody === undefined) {
            throw new runtime.RequiredError('stacksIntrospectionUpdateRequestBody','Required parameter requestParameters.stacksIntrospectionUpdateRequestBody was null or undefined when calling apiV1StacksIntrospectionsUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/stacks/{stack_id}/introspection`.replace(`{${"stack_id"}}`, encodeURIComponent(String(requestParameters.stackId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: StacksIntrospectionUpdateRequestBodyToJSON(requestParameters.stacksIntrospectionUpdateRequestBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StacksIntrospectionsIntrospectionFromJSON(jsonValue));
    }

    /**
     * 積み上げの反省更新API
     */
    async apiV1StacksIntrospectionsUpdate(requestParameters: ApiV1StacksIntrospectionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StacksIntrospectionsIntrospection> {
        const response = await this.apiV1StacksIntrospectionsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
