/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  OutputsCommentsCommentListInner,
} from '../models';
import {
    OutputsCommentsCommentListInnerFromJSON,
    OutputsCommentsCommentListInnerToJSON,
} from '../models';

export interface ApiV1OutputsCommentsIndexRequest {
    outputId: number;
}

/**
 * 
 */
export class OutputCommentApi extends runtime.BaseAPI {

    /**
     * アウトプットのコメント一覧
     */
    async apiV1OutputsCommentsIndexRaw(requestParameters: ApiV1OutputsCommentsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OutputsCommentsCommentListInner>>> {
        if (requestParameters.outputId === null || requestParameters.outputId === undefined) {
            throw new runtime.RequiredError('outputId','Required parameter requestParameters.outputId was null or undefined when calling apiV1OutputsCommentsIndex.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/outputs/{output_id}/comments`.replace(`{${"output_id"}}`, encodeURIComponent(String(requestParameters.outputId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OutputsCommentsCommentListInnerFromJSON));
    }

    /**
     * アウトプットのコメント一覧
     */
    async apiV1OutputsCommentsIndex(requestParameters: ApiV1OutputsCommentsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OutputsCommentsCommentListInner>> {
        const response = await this.apiV1OutputsCommentsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
