/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UsersPlanListInner,
} from '../models';
import {
    UsersPlanListInnerFromJSON,
    UsersPlanListInnerToJSON,
} from '../models';

export interface ApiV1UsersPlansIndexRequest {
    userId: number;
    dateFrom?: Date;
    dateTo?: Date;
}

/**
 * 
 */
export class UserPlanApi extends runtime.BaseAPI {

    /**
     * 計画一覧
     */
    async apiV1UsersPlansIndexRaw(requestParameters: ApiV1UsersPlansIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<Array<UsersPlanListInner>>; }>> {
        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling apiV1UsersPlansIndex.');
        }

        const queryParameters: any = {};

        if (requestParameters.dateFrom !== undefined) {
            queryParameters['date_from'] = (requestParameters.dateFrom as any).toISOString();
        }

        if (requestParameters.dateTo !== undefined) {
            queryParameters['date_to'] = (requestParameters.dateTo as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/users/{user_id}/plans`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * 計画一覧
     */
    async apiV1UsersPlansIndex(requestParameters: ApiV1UsersPlansIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<Array<UsersPlanListInner>>; }> {
        const response = await this.apiV1UsersPlansIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
