/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLogin
 */
export interface AuthLogin {
    /**
     * アクセストークンタイプ
     * @type {string}
     * @memberof AuthLogin
     */
    tokenType: string;
    /**
     * アクセストークン
     * @type {string}
     * @memberof AuthLogin
     */
    accessToken: string;
    /**
     * ユーザーID
     * @type {number}
     * @memberof AuthLogin
     */
    userId?: number;
    /**
     * 有効期限切れまでの秒数
     * @type {number}
     * @memberof AuthLogin
     */
    exp?: number;
}

/**
 * Check if a given object implements the AuthLogin interface.
 */
export function instanceOfAuthLogin(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tokenType" in value;
    isInstance = isInstance && "accessToken" in value;

    return isInstance;
}

export function AuthLoginFromJSON(json: any): AuthLogin {
    return AuthLoginFromJSONTyped(json, false);
}

export function AuthLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenType': json['token_type'],
        'accessToken': json['access_token'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
        'exp': !exists(json, 'exp') ? undefined : json['exp'],
    };
}

export function AuthLoginToJSON(value?: AuthLogin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token_type': value.tokenType,
        'access_token': value.accessToken,
        'user_id': value.userId,
        'exp': value.exp,
    };
}

