/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginRequestBody
 */
export interface AuthLoginRequestBody {
    /**
     * ユーザーのメールアドレス
     * @type {string}
     * @memberof AuthLoginRequestBody
     */
    email: string;
    /**
     * ユーザーのパスワード
     * @type {string}
     * @memberof AuthLoginRequestBody
     */
    password: string;
}

/**
 * Check if a given object implements the AuthLoginRequestBody interface.
 */
export function instanceOfAuthLoginRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthLoginRequestBodyFromJSON(json: any): AuthLoginRequestBody {
    return AuthLoginRequestBodyFromJSONTyped(json, false);
}

export function AuthLoginRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthLoginRequestBodyToJSON(value?: AuthLoginRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

