/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputsImagesImage
 */
export interface OutputsImagesImage {
    /**
     * アウトプット画像ID
     * @type {number}
     * @memberof OutputsImagesImage
     */
    id: number;
    /**
     * アウトプット画像のS3ファイルパス
     * @type {string}
     * @memberof OutputsImagesImage
     */
    path: string;
}

/**
 * Check if a given object implements the OutputsImagesImage interface.
 */
export function instanceOfOutputsImagesImage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "path" in value;

    return isInstance;
}

export function OutputsImagesImageFromJSON(json: any): OutputsImagesImage {
    return OutputsImagesImageFromJSONTyped(json, false);
}

export function OutputsImagesImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputsImagesImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'path': json['path'],
    };
}

export function OutputsImagesImageToJSON(value?: OutputsImagesImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'path': value.path,
    };
}

