/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputCreateRequestBody
 */
export interface OutputCreateRequestBody {
    /**
     * アウトプット内容
     * @type {string}
     * @memberof OutputCreateRequestBody
     */
    content: string;
}

/**
 * Check if a given object implements the OutputCreateRequestBody interface.
 */
export function instanceOfOutputCreateRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function OutputCreateRequestBodyFromJSON(json: any): OutputCreateRequestBody {
    return OutputCreateRequestBodyFromJSONTyped(json, false);
}

export function OutputCreateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputCreateRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function OutputCreateRequestBodyToJSON(value?: OutputCreateRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}

