/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputCommentCreateRequestBody
 */
export interface OutputCommentCreateRequestBody {
    /**
     * アウトプットへのコメント内容
     * @type {string}
     * @memberof OutputCommentCreateRequestBody
     */
    content: string;
    /**
     * ユーザーID
     * @type {number}
     * @memberof OutputCommentCreateRequestBody
     */
    userId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof OutputCommentCreateRequestBody
     */
    imageIds?: Array<number>;
}

/**
 * Check if a given object implements the OutputCommentCreateRequestBody interface.
 */
export function instanceOfOutputCommentCreateRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function OutputCommentCreateRequestBodyFromJSON(json: any): OutputCommentCreateRequestBody {
    return OutputCommentCreateRequestBodyFromJSONTyped(json, false);
}

export function OutputCommentCreateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputCommentCreateRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
        'userId': json['user_id'],
        'imageIds': !exists(json, 'image_ids') ? undefined : json['image_ids'],
    };
}

export function OutputCommentCreateRequestBodyToJSON(value?: OutputCommentCreateRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'user_id': value.userId,
        'image_ids': value.imageIds,
    };
}

