/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OutputsOutputUser } from './OutputsOutputUser';
import {
    OutputsOutputUserFromJSON,
    OutputsOutputUserFromJSONTyped,
    OutputsOutputUserToJSON,
} from './OutputsOutputUser';

/**
 * 
 * @export
 * @interface OutputsOutputListInner
 */
export interface OutputsOutputListInner {
    /**
     * アウトプットID
     * @type {number}
     * @memberof OutputsOutputListInner
     */
    id: number;
    /**
     * アウトプット内容
     * @type {string}
     * @memberof OutputsOutputListInner
     */
    content: string;
    /**
     * 
     * @type {OutputsOutputUser}
     * @memberof OutputsOutputListInner
     */
    user: OutputsOutputUser;
    /**
     * 
     * @type {Date}
     * @memberof OutputsOutputListInner
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof OutputsOutputListInner
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the OutputsOutputListInner interface.
 */
export function instanceOfOutputsOutputListInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function OutputsOutputListInnerFromJSON(json: any): OutputsOutputListInner {
    return OutputsOutputListInnerFromJSONTyped(json, false);
}

export function OutputsOutputListInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputsOutputListInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'user': OutputsOutputUserFromJSON(json['user']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function OutputsOutputListInnerToJSON(value?: OutputsOutputListInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'content': value.content,
        'user': OutputsOutputUserToJSON(value.user),
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}

