/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillsSkill
 */
export interface SkillsSkill {
    /**
     * スキルID
     * @type {number}
     * @memberof SkillsSkill
     */
    id: number;
    /**
     * スキル名
     * @type {string}
     * @memberof SkillsSkill
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof SkillsSkill
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SkillsSkill
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the SkillsSkill interface.
 */
export function instanceOfSkillsSkill(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function SkillsSkillFromJSON(json: any): SkillsSkill {
    return SkillsSkillFromJSONTyped(json, false);
}

export function SkillsSkillFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillsSkill {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SkillsSkillToJSON(value?: SkillsSkill | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}

