/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StacksCreateRequestBody
 */
export interface StacksCreateRequestBody {
    /**
     * 積み上げタイトル
     * @type {string}
     * @memberof StacksCreateRequestBody
     */
    title: string;
    /**
     * 積み上げ時間
     * @type {number}
     * @memberof StacksCreateRequestBody
     */
    minutes: number;
    /**
     * スキルID
     * @type {number}
     * @memberof StacksCreateRequestBody
     */
    skillId: number;
    /**
     * ユーザーID
     * @type {number}
     * @memberof StacksCreateRequestBody
     */
    userId: number;
    /**
     * 積み上げ内容
     * @type {string}
     * @memberof StacksCreateRequestBody
     */
    description: string | null;
    /**
     * 
     * @type {Date}
     * @memberof StacksCreateRequestBody
     */
    stackedAt: Date;
    /**
     * 完了したかどうか
     * @type {boolean}
     * @memberof StacksCreateRequestBody
     */
    completed: boolean;
}

/**
 * Check if a given object implements the StacksCreateRequestBody interface.
 */
export function instanceOfStacksCreateRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "minutes" in value;
    isInstance = isInstance && "skillId" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "stackedAt" in value;
    isInstance = isInstance && "completed" in value;

    return isInstance;
}

export function StacksCreateRequestBodyFromJSON(json: any): StacksCreateRequestBody {
    return StacksCreateRequestBodyFromJSONTyped(json, false);
}

export function StacksCreateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StacksCreateRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'minutes': json['minutes'],
        'skillId': json['skill_id'],
        'userId': json['user_id'],
        'description': json['description'],
        'stackedAt': (new Date(json['stacked_at'])),
        'completed': json['completed'],
    };
}

export function StacksCreateRequestBodyToJSON(value?: StacksCreateRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'minutes': value.minutes,
        'skill_id': value.skillId,
        'user_id': value.userId,
        'description': value.description,
        'stacked_at': (value.stackedAt.toISOString()),
        'completed': value.completed,
    };
}

