/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StacksIntrospectionsKeepsKeep
 */
export interface StacksIntrospectionsKeepsKeep {
    /**
     * 反省のKeepID
     * @type {number}
     * @memberof StacksIntrospectionsKeepsKeep
     */
    id: number;
    /**
     * 反省のKeep項目
     * @type {string}
     * @memberof StacksIntrospectionsKeepsKeep
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof StacksIntrospectionsKeepsKeep
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof StacksIntrospectionsKeepsKeep
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the StacksIntrospectionsKeepsKeep interface.
 */
export function instanceOfStacksIntrospectionsKeepsKeep(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function StacksIntrospectionsKeepsKeepFromJSON(json: any): StacksIntrospectionsKeepsKeep {
    return StacksIntrospectionsKeepsKeepFromJSONTyped(json, false);
}

export function StacksIntrospectionsKeepsKeepFromJSONTyped(json: any, ignoreDiscriminator: boolean): StacksIntrospectionsKeepsKeep {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function StacksIntrospectionsKeepsKeepToJSON(value?: StacksIntrospectionsKeepsKeep | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'content': value.content,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}

