/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StacksIntrospectionCreateRequestBody
 */
export interface StacksIntrospectionCreateRequestBody {
    /**
     * 積み上げの評価
     * @type {number}
     * @memberof StacksIntrospectionCreateRequestBody
     */
    evaluation: number;
    /**
     * 積み上げの評価理由
     * @type {string}
     * @memberof StacksIntrospectionCreateRequestBody
     */
    reason: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StacksIntrospectionCreateRequestBody
     */
    keepContents: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StacksIntrospectionCreateRequestBody
     */
    problemContents: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StacksIntrospectionCreateRequestBody
     */
    tryContents: Array<string>;
}

/**
 * Check if a given object implements the StacksIntrospectionCreateRequestBody interface.
 */
export function instanceOfStacksIntrospectionCreateRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "evaluation" in value;
    isInstance = isInstance && "reason" in value;
    isInstance = isInstance && "keepContents" in value;
    isInstance = isInstance && "problemContents" in value;
    isInstance = isInstance && "tryContents" in value;

    return isInstance;
}

export function StacksIntrospectionCreateRequestBodyFromJSON(json: any): StacksIntrospectionCreateRequestBody {
    return StacksIntrospectionCreateRequestBodyFromJSONTyped(json, false);
}

export function StacksIntrospectionCreateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StacksIntrospectionCreateRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'evaluation': json['evaluation'],
        'reason': json['reason'],
        'keepContents': json['keep_contents'],
        'problemContents': json['problem_contents'],
        'tryContents': json['try_contents'],
    };
}

export function StacksIntrospectionCreateRequestBodyToJSON(value?: StacksIntrospectionCreateRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'evaluation': value.evaluation,
        'reason': value.reason,
        'keep_contents': value.keepContents,
        'problem_contents': value.problemContents,
        'try_contents': value.tryContents,
    };
}

