/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamUpdateRequestBody
 */
export interface TeamUpdateRequestBody {
    /**
     * グループ名
     * @type {string}
     * @memberof TeamUpdateRequestBody
     */
    name: string;
}

/**
 * Check if a given object implements the TeamUpdateRequestBody interface.
 */
export function instanceOfTeamUpdateRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TeamUpdateRequestBodyFromJSON(json: any): TeamUpdateRequestBody {
    return TeamUpdateRequestBodyFromJSONTyped(json, false);
}

export function TeamUpdateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamUpdateRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TeamUpdateRequestBodyToJSON(value?: TeamUpdateRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

