/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamsStackRanking
 */
export interface TeamsStackRanking {
    /**
     * 積み上げランキング順位
     * @type {number}
     * @memberof TeamsStackRanking
     */
    order: number;
    /**
     * ユーザー名
     * @type {string}
     * @memberof TeamsStackRanking
     */
    userName: string;
}

/**
 * Check if a given object implements the TeamsStackRanking interface.
 */
export function instanceOfTeamsStackRanking(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "order" in value;
    isInstance = isInstance && "userName" in value;

    return isInstance;
}

export function TeamsStackRankingFromJSON(json: any): TeamsStackRanking {
    return TeamsStackRankingFromJSONTyped(json, false);
}

export function TeamsStackRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamsStackRanking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': json['order'],
        'userName': json['user_name'],
    };
}

export function TeamsStackRankingToJSON(value?: TeamsStackRanking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
        'user_name': value.userName,
    };
}

