/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamInviteRequestBody
 */
export interface TeamInviteRequestBody {
    /**
     * ユーザーのメールアドレス
     * @type {string}
     * @memberof TeamInviteRequestBody
     */
    name: string;
}

/**
 * Check if a given object implements the TeamInviteRequestBody interface.
 */
export function instanceOfTeamInviteRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TeamInviteRequestBodyFromJSON(json: any): TeamInviteRequestBody {
    return TeamInviteRequestBodyFromJSONTyped(json, false);
}

export function TeamInviteRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamInviteRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TeamInviteRequestBodyToJSON(value?: TeamInviteRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

