/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeamsStackRankingListStackRankingsInner } from './TeamsStackRankingListStackRankingsInner';
import {
    TeamsStackRankingListStackRankingsInnerFromJSON,
    TeamsStackRankingListStackRankingsInnerFromJSONTyped,
    TeamsStackRankingListStackRankingsInnerToJSON,
} from './TeamsStackRankingListStackRankingsInner';

/**
 * 
 * @export
 * @interface TeamsStackRankingList
 */
export interface TeamsStackRankingList {
    /**
     * 
     * @type {Array<TeamsStackRankingListStackRankingsInner>}
     * @memberof TeamsStackRankingList
     */
    stackRankings: Array<TeamsStackRankingListStackRankingsInner>;
}

/**
 * Check if a given object implements the TeamsStackRankingList interface.
 */
export function instanceOfTeamsStackRankingList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stackRankings" in value;

    return isInstance;
}

export function TeamsStackRankingListFromJSON(json: any): TeamsStackRankingList {
    return TeamsStackRankingListFromJSONTyped(json, false);
}

export function TeamsStackRankingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamsStackRankingList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stackRankings': ((json['stack_rankings'] as Array<any>).map(TeamsStackRankingListStackRankingsInnerFromJSON)),
    };
}

export function TeamsStackRankingListToJSON(value?: TeamsStackRankingList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stack_rankings': ((value.stackRankings as Array<any>).map(TeamsStackRankingListStackRankingsInnerToJSON)),
    };
}

