/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamsStackRankingListStackRankingsInner
 */
export interface TeamsStackRankingListStackRankingsInner {
    /**
     * 積み上げランキング順位
     * @type {number}
     * @memberof TeamsStackRankingListStackRankingsInner
     */
    order: number;
    /**
     * ユーザー名
     * @type {string}
     * @memberof TeamsStackRankingListStackRankingsInner
     */
    userName: string;
}

/**
 * Check if a given object implements the TeamsStackRankingListStackRankingsInner interface.
 */
export function instanceOfTeamsStackRankingListStackRankingsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "order" in value;
    isInstance = isInstance && "userName" in value;

    return isInstance;
}

export function TeamsStackRankingListStackRankingsInnerFromJSON(json: any): TeamsStackRankingListStackRankingsInner {
    return TeamsStackRankingListStackRankingsInnerFromJSONTyped(json, false);
}

export function TeamsStackRankingListStackRankingsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamsStackRankingListStackRankingsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': json['order'],
        'userName': json['user_name'],
    };
}

export function TeamsStackRankingListStackRankingsInnerToJSON(value?: TeamsStackRankingListStackRankingsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
        'user_name': value.userName,
    };
}

