/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 計画開始時間
 * @export
 * @interface UsersPlansPlanStartTime
 */
export interface UsersPlansPlanStartTime {
}

/**
 * Check if a given object implements the UsersPlansPlanStartTime interface.
 */
export function instanceOfUsersPlansPlanStartTime(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersPlansPlanStartTimeFromJSON(json: any): UsersPlansPlanStartTime {
    return UsersPlansPlanStartTimeFromJSONTyped(json, false);
}

export function UsersPlansPlanStartTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPlansPlanStartTime {
    return json;
}

export function UsersPlansPlanStartTimeToJSON(value?: UsersPlansPlanStartTime | null): any {
    return value;
}

