/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsersUserRole } from './UsersUserRole';
import {
    UsersUserRoleFromJSON,
    UsersUserRoleFromJSONTyped,
    UsersUserRoleToJSON,
} from './UsersUserRole';

/**
 * 
 * @export
 * @interface UsersMinimumUser
 */
export interface UsersMinimumUser {
    /**
     * ユーザーID
     * @type {number}
     * @memberof UsersMinimumUser
     */
    id: number;
    /**
     * ユーザー名
     * @type {string}
     * @memberof UsersMinimumUser
     */
    name: string;
    /**
     * ユーザーのメールアドレス
     * @type {string}
     * @memberof UsersMinimumUser
     */
    email: string;
    /**
     * ユーザーのプロフィール文
     * @type {string}
     * @memberof UsersMinimumUser
     */
    profileContent: string | null;
    /**
     * 
     * @type {UsersUserRole}
     * @memberof UsersMinimumUser
     */
    role: UsersUserRole;
    /**
     * ユーザープロフィール画像のS3ファイルパス
     * @type {string}
     * @memberof UsersMinimumUser
     */
    profileImagePath?: string;
}

/**
 * Check if a given object implements the UsersMinimumUser interface.
 */
export function instanceOfUsersMinimumUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "profileContent" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function UsersMinimumUserFromJSON(json: any): UsersMinimumUser {
    return UsersMinimumUserFromJSONTyped(json, false);
}

export function UsersMinimumUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMinimumUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
        'profileContent': json['profile_content'],
        'role': UsersUserRoleFromJSON(json['role']),
        'profileImagePath': !exists(json, 'profile_image_path') ? undefined : json['profile_image_path'],
    };
}

export function UsersMinimumUserToJSON(value?: UsersMinimumUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'profile_content': value.profileContent,
        'role': UsersUserRoleToJSON(value.role),
        'profile_image_path': value.profileImagePath,
    };
}

