/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPlanCreateRequestBody
 */
export interface UserPlanCreateRequestBody {
    /**
     * ユーザーの計画タイトル
     * @type {string}
     * @memberof UserPlanCreateRequestBody
     */
    title: string;
    /**
     * ユーザーの計画詳細
     * @type {string}
     * @memberof UserPlanCreateRequestBody
     */
    description: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserPlanCreateRequestBody
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserPlanCreateRequestBody
     */
    endTime: Date;
    /**
     * スキルID
     * @type {number}
     * @memberof UserPlanCreateRequestBody
     */
    skillId: number;
}

/**
 * Check if a given object implements the UserPlanCreateRequestBody interface.
 */
export function instanceOfUserPlanCreateRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "startTime" in value;
    isInstance = isInstance && "endTime" in value;
    isInstance = isInstance && "skillId" in value;

    return isInstance;
}

export function UserPlanCreateRequestBodyFromJSON(json: any): UserPlanCreateRequestBody {
    return UserPlanCreateRequestBodyFromJSONTyped(json, false);
}

export function UserPlanCreateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPlanCreateRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
        'skillId': json['skill_id'],
    };
}

export function UserPlanCreateRequestBodyToJSON(value?: UserPlanCreateRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'start_time': (value.startTime.toISOString()),
        'end_time': (value.endTime.toISOString()),
        'skill_id': value.skillId,
    };
}

