/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 計画終了時間
 * @export
 * @interface UsersPlansPlanEndTime
 */
export interface UsersPlansPlanEndTime {
}

/**
 * Check if a given object implements the UsersPlansPlanEndTime interface.
 */
export function instanceOfUsersPlansPlanEndTime(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersPlansPlanEndTimeFromJSON(json: any): UsersPlansPlanEndTime {
    return UsersPlansPlanEndTimeFromJSONTyped(json, false);
}

export function UsersPlansPlanEndTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPlansPlanEndTime {
    return json;
}

export function UsersPlansPlanEndTimeToJSON(value?: UsersPlansPlanEndTime | null): any {
    return value;
}

