/* tslint:disable */
/* eslint-disable */
/**
 * Skill Climbing
 * スキルの積み上げアプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SkillRanksSkillRankName } from './SkillRanksSkillRankName';
import {
    SkillRanksSkillRankNameFromJSON,
    SkillRanksSkillRankNameFromJSONTyped,
    SkillRanksSkillRankNameToJSON,
} from './SkillRanksSkillRankName';
import type { StacksStackSkill } from './StacksStackSkill';
import {
    StacksStackSkillFromJSON,
    StacksStackSkillFromJSONTyped,
    StacksStackSkillToJSON,
} from './StacksStackSkill';

/**
 * 
 * @export
 * @interface UsersUserSkillRanksInner
 */
export interface UsersUserSkillRanksInner {
    /**
     * スキルランクID
     * @type {number}
     * @memberof UsersUserSkillRanksInner
     */
    id: number;
    /**
     * 
     * @type {SkillRanksSkillRankName}
     * @memberof UsersUserSkillRanksInner
     */
    name: SkillRanksSkillRankName;
    /**
     * 
     * @type {StacksStackSkill}
     * @memberof UsersUserSkillRanksInner
     */
    skill: StacksStackSkill;
    /**
     * 
     * @type {Date}
     * @memberof UsersUserSkillRanksInner
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsersUserSkillRanksInner
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UsersUserSkillRanksInner interface.
 */
export function instanceOfUsersUserSkillRanksInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "skill" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function UsersUserSkillRanksInnerFromJSON(json: any): UsersUserSkillRanksInner {
    return UsersUserSkillRanksInnerFromJSONTyped(json, false);
}

export function UsersUserSkillRanksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersUserSkillRanksInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': SkillRanksSkillRankNameFromJSON(json['name']),
        'skill': StacksStackSkillFromJSON(json['skill']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function UsersUserSkillRanksInnerToJSON(value?: UsersUserSkillRanksInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': SkillRanksSkillRankNameToJSON(value.name),
        'skill': StacksStackSkillToJSON(value.skill),
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}

